version: 2

jobs:
  test:
    docker:
      - image: busybox
    steps:
      - run: 'true'

  release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run semantic-release

workflows:
  version: 2
  test-and-release:
    jobs:
      - test
      - release:
          requires:
            - test
